# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration for YNAB MCP Server
# Focus: Security and Safety

language: "en-US"
tone_instructions: "Be thorough about security issues. Flag any potential vulnerabilities clearly."
early_access: false

reviews:
  profile: "assertive"  # Strict reviews for security focus
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  review_status: true
  commit_status: true
  fail_commit_status: true  # Fail on security issues
  collapse_walkthrough: false
  sequence_diagrams: true

  # Path-specific security instructions
  path_instructions:
    - path: "src/**/*.ts"
      instructions: |
        Security Review Checklist:
        1. INPUT VALIDATION: Ensure all user inputs are validated with Zod schemas before use
        2. API TOKENS: Never log, expose, or hardcode YNAB_ACCESS_TOKEN or any credentials
        3. ERROR MESSAGES: Verify error messages don't leak sensitive information (tokens, internal paths)
        4. RATE LIMITING: Confirm API calls go through rateLimiter.acquire()
        5. READ-ONLY MODE: Write operations must call assertWriteAllowed() before execution
        6. AUDIT LOGGING: All write operations must be logged via auditLog
        7. SQL/COMMAND INJECTION: Check for any string interpolation that could allow injection
        8. TYPE SAFETY: Ensure proper TypeScript types, avoid 'any' type

    - path: "src/services/ynab-client.ts"
      instructions: |
        CRITICAL FILE - YNAB API Client
        - Verify all write operations check assertWriteAllowed()
        - Confirm rateLimiter.acquire() is called before every API request
        - Ensure tokens are never logged or included in error messages
        - Check that audit logging captures all mutations

    - path: "src/tools/**/*.ts"
      instructions: |
        Tool Handler Security:
        - Validate ALL inputs with Zod before processing
        - Sanitize any user-provided strings before including in responses
        - Don't expose internal IDs or paths unnecessarily
        - Ensure budget_id resolution uses client.resolveBudgetId()

    - path: "src/config/**/*.ts"
      instructions: |
        Configuration Security:
        - Environment variables must be validated
        - Sensitive values (tokens) must never have defaults
        - READ_ONLY should default to true for safety

    - path: "tests/**/*.ts"
      instructions: |
        Test Security:
        - Never use real API tokens in tests
        - Mock all external API calls
        - Test error handling paths for information leakage

  # Auto review settings
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false

  # Pre-merge security checks
  pre_merge_checks:
    title:
      mode: "warning"
    description:
      mode: "warning"
    custom_checks:
      - mode: "error"
        name: "No Hardcoded Secrets"
        instructions: |
          FAIL if any of these are found:
          - Hardcoded API tokens or keys
          - Hardcoded passwords
          - YNAB access tokens in code (not from environment)
          - Base64 encoded credentials

      - mode: "error"
        name: "Input Validation"
        instructions: |
          FAIL if tool handlers don't validate inputs with Zod schemas
          before processing user-provided data.

      - mode: "error"
        name: "Rate Limit Compliance"
        instructions: |
          FAIL if any new API calls are added without calling
          rateLimiter.acquire() first.

      - mode: "warning"
        name: "Error Message Safety"
        instructions: |
          WARN if error messages might expose:
          - Internal file paths
          - API tokens or credentials
          - Stack traces with sensitive context
          - Database/API internal IDs

  # Enable security-focused tools
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    biome:
      enabled: true
    ast-grep:
      essential_rules: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  learnings:
    scope: "local"
  issues:
    scope: "local"
  pull_requests:
    scope: "local"
